# Generated by Django 6.0.5 on 2026-05-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='allocation_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual alocado para essa categoria', max_digits=5),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
