# Generated by Django 6.0.5 on 2026-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_budget_allocation_percent_alter_budget_category'),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM app_budget WHERE category_id IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='budget',
            name='allocation_percent',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=models.CASCADE, to='app.category'),
        ),
    ]
