# Generated by Django 6.0.5 on 2026-05-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20260513_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='income_source',
            field=models.CharField(blank=True, default='', help_text='Para receitas: Salário, Bolsa, etc. (independente da categoria contábil)', max_length=100),
        ),
    ]
