# Generated by Django 5.2.14 on 2026-05-16 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transaction_income_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10)),
                ('income_source', models.CharField(blank=True, default='', help_text='Para receitas: Salário, Bolsa, etc.', max_length=100)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensal'), ('weekly', 'Semanal')], default='monthly', max_length=10)),
                ('due_day', models.PositiveSmallIntegerField(help_text='Mensal: dia 1–31. Semanal: 0=segunda … 6=domingo (padrão Python).')),
                ('start_date', models.DateField(help_text='A partir desta data a recorrência passa a gerar lançamentos.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação recorrente',
                'verbose_name_plural': 'Transações recorrentes',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='app.recurringtransaction'),
        ),
    ]
