# Generated by Django 5.2.14 on 2026-05-18 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_recurring_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
