# Generated by Django 5.2.14 on 2026-05-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_alert_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('orcamento_80', 'Orçamento 80%'), ('orcamento_100', 'Orçamento 100%'), ('orcamento_limite', 'Orçamento no Limite'), ('meta_prazo', 'Meta com Prazo'), ('meta_vencida', 'Meta Vencida'), ('meta_concluida', 'Meta Concluída'), ('saldo_negativo', 'Saldo Negativo'), ('saldo_projetado', 'Saldo Projetado Negativo')], max_length=20),
        ),
    ]
