# Generated by Django 5.2.14 on 2026-05-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_alert_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='state_hash',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('orcamento_80', 'Orçamento 80%'), ('orcamento_100', 'Orçamento 100%'), ('meta_prazo', 'Meta com Prazo'), ('saldo_negativo', 'Saldo Negativo')], max_length=20),
        ),
    ]
